### ISSUE TITLE
ChatControl Not starting up on 1.8 after update to 7.9.1

### ISSUE THREAD

**Issue by starwarsfreak219** [kangarko/ChatControl-Pro#833]
I get this error when I updated ChatControl from 7.8.30 or 7.9.0-BETA to 7.9.1 on my 1.8 server: 
15.07 20:16:51 [Server] INFO java.lang.NoClassDefFoundError: org/bukkit/Particle
15.07 20:16:51 [Server] INFO at me.kangarko.chatcontrol.final. .pRn.onEnable(SourceFile:166)
15.07 20:16:51 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
15.07 20:16:51 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
15.07 20:16:51 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
15.07 20:16:51 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
15.07 20:16:51 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
15.07 20:16:51 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
15.07 20:16:51 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
15.07 20:16:51 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
15.07 20:16:51 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
15.07 20:16:51 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
15.07 20:16:51 [Server] INFO at java.lang.Thread.run(Unknown Source)
15.07 20:16:51 [Server] INFO java.lang.ClassNotFoundException: org.bukkit.Particle
15.07 20:16:51 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
15.07 20:16:51 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
15.07 20:16:51 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source)
15.07 20:16:51 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source)
15.07 20:16:51 [Server] INFO at me.kangarko.chatcontrol.final. .pRn.onEnable(SourceFile:166)
15.07 20:16:51 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
15.07 20:16:51 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
15.07 20:16:51 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
15.07 20:16:51 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
15.07 20:16:51 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
15.07 20:16:51 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
15.07 20:16:51 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
15.07 20:16:51 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
15.07 20:16:51 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
15.07 20:16:51 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
15.07 20:16:51 [Server] INFO at java.lang.Thread.run(Unknown Source)
15.07 20:16:51 [Server] INFO _   _                       _ 
15.07 20:16:51 [Server] INFO | | | | ___   ___  _ __  ___| |
15.07 20:16:51 [Server] INFO | |_| |/ _ \ / _ \| '_ \/ __| |
15.07 20:16:51 [Server] INFO |  _  | (_) | (_) | |_) \__ \_|
15.07 20:16:51 [Server] INFO |_| |_|\___/ \___/| .__/|___(_)
15.07 20:16:51 [Server] INFO |_|          
15.07 20:16:51 [Server] INFO !-----------------------------------------------------!
15.07 20:16:51 [Server] INFO Error loading ChatControl v7.9.1, plugin is disabled!
15.07 20:16:51 [Server] INFO Running on 1.8.8-R0.1-SNAPSHOT (v1_8_R3) & Java 1.8.0_162
15.07 20:16:51 [Server] INFO !-----------------------------------------------------!
15.07 20:16:51 [Server] INFO Error: org.bukkit.Particle
15.07 20:16:51 [Server] INFO !-----------------------------------------------------!
15.07 20:16:51 [Server] INFO Disabling ChatControl v7.9.1
15.07 20:16:51 [Server] INFO Plugin might not shut down property. Got NullPointerException: null
15.07 20:16:51 [Server] WARN java.lang.NoClassDefFoundError: org/bukkit/Particle
15.07 20:16:51 [Server] WARN at me.kangarko.chatcontrol.final. .pRn.onDisable(SourceFile:418)
15.07 20:16:51 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323)
15.07 20:16:51 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364)
15.07 20:16:51 [Server] WARN at me.kangarko.chatcontrol.final. .pRn.native(SourceFile:381)
15.07 20:16:51 [Server] WARN at me.kangarko.chatcontrol.final. .pRn.onEnable(SourceFile:224)
15.07 20:16:51 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
15.07 20:16:51 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
15.07 20:16:51 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
15.07 20:16:51 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
15.07 20:16:51 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
15.07 20:16:51 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
15.07 20:16:51 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
15.07 20:16:51 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
15.07 20:16:51 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
15.07 20:16:51 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
15.07 20:16:51 [Server] WARN at java.lang.Thread.run(Unknown Source)
15.07 20:16:51 [Server] WARN Caused by: java.lang.ClassNotFoundException: org.bukkit.Particle
15.07 20:16:51 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
15.07 20:16:51 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
15.07 20:16:51 [Server] WARN at java.lang.ClassLoader.loadClass(Unknown Source)
15.07 20:16:51 [Server] WARN at java.lang.ClassLoader.loadClass(Unknown Source)
15.07 20:16:51 [Server] WARN ... 16 more

**Comment by MrDisastrous** [comment]
Same issue here

**Comment by ArtelGG** [comment]
Duplicate report of #828

**Comment by kangarko** [comment]
Thank you very much for reporting. This is solved in 7.9.2 rev.2 update.
